web_h_10/hm_project/hm_project/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

web_h_10/hm_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root.paginate"),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('about_author/<str:fullname>', views.aboutauthor, name='about_author'),
]

web_h_10/hm_project/users/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

web_h_10/hm_project/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

web_h_10/hm_project/users/models.py
from django.db import models

# Create your models here.

web_h_10/hm_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Quote, Author


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput())
    author = CharField(required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=100, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_location = CharField(min_length=3, max_length=150, required=True, widget=TextInput())
    description = CharField(required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

web_h_10/hm_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

web_h_10/hm_project/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .forms import QuoteForm, AuthorForm
from .models import Author
from .utils import get_mongodb

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})
def quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/quote.html', {'form': form})

    return render(request, 'quotes/quote.html', {'form': QuoteForm()})


def author(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/author.html', {'form': form})

    return render(request, 'quotes/author.html', {'form': AuthorForm()})


def aboutauthor(request, fullname):
    aut = get_object_or_404(Author, fullmane=fullname)
    return render(request, 'quotes/page_of_author.html', {'author': aut})

web_h_10/hm_project/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

web_h_10/hm_project/quotes/templates/quotes/author's_page.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container">


<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

    </div>

{% endblock %}

web_h_10/hm_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author's fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's date of born:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the description about author:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web_h_10/hm_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content=""ie="edge">
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>Homework</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                <a href="/login" class="btn btn-primary">SignUp</a>
                <a href="/login" class="btn btn-primary">Login</a>
                <a href="/login" class="btn btn-primary">Logout</a>


            </p>
        </div>
    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

web_h_10/hm_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
            <div class="tags">
                Tags:

                {% for tag in quote.tags %}

                <a class="tag" href="/tag/change/page/1/">change</a>
                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">


                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>

                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>




{% endblock %}



web_h_10/hm_project/quotes/templates/quotes/quote.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
      <div style="padding: 10px">
        <label>Enter the author fullname:
            {{form.author}}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web_h_10/hm_project/users/templates/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web_h_10/hm_project/users/templates/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}
